<?php

namespace Database\Seeders;

use App\Models\Game;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PragmaticNormalizeGames extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $games = $this->games();
        $count = 0;
        foreach ($games as $id => $game) {
            $gameExist = Game::query()
                ->where('provider_id', 1)
                ->where(function ($query) use ($game, $id) {
                    $query->where('game_name', 'like', "%{$game}%")
                        ->orWhere('game_code', $id)
                        ->orWhere('game_id', $id);

                })
                ->first();
            if ($gameExist === null) {
                continue;
            }
            if ($count < 6) {
                $gameExist->show_home = true;
            }
            $gameExist->game_id = $id;
            $gameExist->distribution = "games_api";
            $gameExist->status = 1;
            $gameExist->save();
            $count++;
        }

        Game::query()
            ->where('provider_id', 1)
            ->where("distribution", '!=', 'games_api')
            ->update(["status" => false]);
    }

    public function games()
    {
        return [
            "vs20olympgate" => "Gates of Olympus",
            "vs20sugarrush" => "Sugar Rush",
            "vs20starlight" => "Starlight Princess",
            "vs20fruitsw" => "Sweet Bonanza",
            "vswayslions" => "5 Lions Megaways",
            "vswaysdogs" => "The Dog House Megaways",
            "vs20sbxmas" => "Sweet Bonanza Xmas",
            "vs40wildwest" => "Wild West Gold",
            "vs20fruitparty" => "Fruit Party",
            "vs5aztecgems" => "Aztec Gems",
            "vs20doghouse" => "The Dog House",
            "vswaysrhino" => "Great Rhino Megaways",
            "vswaysbufking" => "Buffalo King Megaways",
            "vs20farmfest" => "Barn Festival",
            "vs25pandatemple" => "Panda Fortune 2",
            "vs20cleocatra" => "Cleocatra",
            "vs20doghousemh" => "The Dog House Multihold",
            "vswaysmadame" => "Madame Destiny Megaways",
            "vs243nudge4gold" => "Hellvis Wild",
            "vs10bbextreme" => "Big Bass Amazon Xtreme",
            "vs20midas" => "The Hand of Midas",
            "vs20beefed" => "Fat Panda",
            "vs20jewelparty" => "Jewel Rush",
            "vs9outlaw" => "Pirates Pub",
            "vs20lampinf" => "Lamp Of Infinity",
            "vs20clustwild" => "Sticky Bees",
            "vs20muertos" => "Muertos Multiplier Megaways",
            "vs243lionsgold" => "5 Lions Gold",
            "vs25spotz" => "Knight Hot Spotz",
            "vs20excalibur" => "Excalibur Unleashed",
            "vs20stickywild" => "Wild Bison Charge",
            "vswayseternity" => "Diamonds of Egypt",
            "vs20mvwild" => "Jasmine Dreams",
            "vswaysrsm" => "Wild Celebrity Bus Megaways",
            "vswaysmonkey" => "3 Dancing Monkeys",
            "vs20hotzone" => "African Elephant",
            "vswaysredqueen" => "The Red Queen",
            "vs20sknights" => "The Knight King",
            "vs20goldclust" => "Rabbit Garden",
            "vs20pistols" => "Wild West Duels",
            "vs10powerlines" => "Peak Power",
            "vswayswwriches" => "Wild Wild Riches Megaways",
            "vs12tropicana" => "Club Tropicana",
            "vs25archer" => "Fire Archer",
            "vs20mochimon" => "Mochimon",
            "vswaysstrwild" => "Candy Stars",
            "vs10fisheye" => "Fish Eye",
            "vs20superlanche" => "Monster Superlanche",
            "vs25spgldways" => "Secret City Gold",
            "vs20ltng" => "Pinup Girls",
            "vs20mammoth" => "Mammoth Gold Megaways",
            "vswayswwhex" => "Wild Wild Bananas",
            "vs20dugems" => "Hot Pepper",
            "vs20clspwrndg" => "Sweet Powernudge",
            "vs25rlbank" => "Reel Banks",
            "vswayspizza" => "PIZZA PIZZA PIZZA",
            "vs20drgbless" => "Dragon Hero",
            "vs12bbb" => "Bigger Bass Bonanza",
            "vs4096bufking" => "Buffalo King",
            "vs20mtreasure" => "Pirate Golden Age",
            "vs20wildparty" => "3 Buzzing Wilds",
            "vs20theights" => "Towering Fortunes",
            "vs25kfruit" => "Aztec Blaze",
            "vs7776aztec" => "Aztec Bonanza",
            "vs1dragon8" => "888 Dragons",
            "vswaysjkrdrop" => "Tropical Tiki",
            "vs10txbigbass" => "Big Bass Splash",
            "vs10floatdrg" => "Floating Dragon",
            "vs5strh" => "Striking Hot 5",
            "vs20trswild2" => "Black Bull",
            "vs10mmm" => "Magic Money Maze",
            "vs20wolfie" => "Greedy Wolf",
            "vs5firehot" => "Fire Hot 5",
            "vs20fh" => "Fire Hot 20",
            "vs40firehot" => "Fire Hot 40",
            "vs1024gmayhem" => "Gorilla Mayhem",
            "vs20octobeer" => "Octobeer Fortunes",
            "vs9aztecgemsdx" => "Aztec Gems Deluxe",
            "vswayswildwest" => "Wild West Gold Megaways",
            "vswaysxjuicy" => "Extra Juicy Megaways",
            "vs20xmascarol" => "Christmas Carol Megaways",
            "vswayslight" => "Lucky Lightning",
            "vs25bomb" => "Bomb Bonanza",
            "vs15diamond" => "Diamond Strike",
            "vs25hotfiesta" => "Hot Fiesta",
            "vs20goldfever" => "Gems Bonanza",
            "vs10firestrike" => "Fire Strike",
            "vs10bbbonanza" => "Big Bass Bonanza",
            "vs5sh" => "Shining Hot 5",
            "vs20sh" => "Shining Hot 20",
            "vs40sh" => "Shining Hot 40",
            "vswayszombcarn" => "Zombie Carnival",
            "vs50northgard" => "North Guardians",
            "vs40cosmiccash" => "Cosmic Cash",
            "vs20gobnudge" => "Goblin Heist Powernudge",
            "vs10firestrike2" => "Fire Strike 2",
            "vs20drtgold" => "Drill That Gold",
            "vs20trsbox" => "Treasure Wild",
            "vs20mustanggld2" => "Clover Gold",
            "vs25goldparty" => "Gold Party",
            "vswayselements" => "Elemental Gems Megaways",
            "vs20superx" => "Super X",
            "vs20fparty2" => "Fruit Party 2",
            "vs20phoenixf" => "Phoenix Forge",
            "vswayscryscav" => "Crystal Caverns Megaways",
            "vs25copsrobbers" => "Cash Patrol",
            "vs243queenie" => "Queenie",
            "vswaysbbb" => "Big Bass Bonanza Megaways",
            "vs20bchprty" => "Wild Beach Party",
            "vs243lions" => "5 Lions",
            "vswaysyumyum" => "Yum Yum Powerways",
            "vs1024temuj" => "Temujin Treasures",
            "vs20rhinoluxe" => "Great Rhino Deluxe",
            "vs25btygold" => "Bounty Gold",
            "vs50juicyfr" => "Juicy Fruits",
            "vs20rhino" => "Great Rhino",
            "vs7fire88" => "Fire 88",
            "vs20chickdrop" => "Chicken Drop",
            "vs20ultim5" => "The Ultimate 5",
            "vs243fortseren" => "Greek Gods",
            "vs1masterjoker" => "Master Joker",
            "vs20rockvegas" => "Rock Vegas",
            "vs576treasures" => "Wild Wild Riches",
            "vs40spartaking" => "Spartan King",
            "vs10chkchase" => "Chicken Chase",
            "vs10tictac" => "Tic Tac Take",
            "vs20rainbowg" => "Rainbow Gold",
            "vs10egyptcls" => "Ancient Egypt Classic",
            "vs40pirate" => "Pirate Gold",
            "vs10fruity2" => "Extra Juicy",
            "vs10eyestorm" => "Eye of the Storm",
            "vs243mwarrior" => "Monkey Warrior",
            "vs25mustang" => "Mustang Gold",
            "vs25chilli" => "Chilli Heat",
            "bjmb" => "American Blackjack",
            "vs5ultrab" => "Ultra Burn",
            "vs25mmouse" => "Money Mouse",
            "vs40bigjuan" => "Big Juan",
            "vswayschilheat" => "Chilli Heat Megaways",
            "vs1024lionsd" => "5 Lions Dance",
            "vs25pyramid" => "Pyramid King",
            "vs20vegasmagic" => "Vegas Magic",
            "bjma" => "Multihand Blackjack",
            "vs432congocash" => "Congo Cash",
            "vs20colcashzone" => "Colossal Cash Zone",
            "vs243dancingpar" => "Dance Party",
            "vs9piggybank" => "Piggy Bank Bills",
            "vs25wolfgold" => "Wolf Gold",
            "bca" => "Baccarat",
            "vs20wildboost" => "Wild Booster",
            "vs25wildspells" => "Wild Spells",
            "vs5super7" => "Super 7s ",
            "vs40pirgold" => "Pirate Gold Deluxe",
            "vs1tigers" => "Triple Tigers",
            "vs10wildtut" => "Mysterious Egypt",
            "vs25newyear" => "Lucky New Year",
            "vswayswest" => "Mystic Chief",
            "vs25peking" => "Peking Luck",
            "vs20smugcove" => "Smugglers Cove",
            "vs25asgard" => "Asgard",
            "vs25goldrush" => "Gold Rush",
            "vs5spjoker" => "Super Joker",
            "vs1024butterfly" => "Jade Butterfly",
            "vs10madame" => "Madame Destiny",
            "vs25vegas" => "Vegas Nights",
            "vswayshive" => "Star Bounty",
            "vs25jokerking" => "Joker King",
            "vs10threestar" => "Three Star Fortune",
            "vs40voodoo" => "Voodoo Magic",
            "vs25dragonkingdom" => "Dragon Kingdom",
            "vs10goldfish" => "Fishin Reels",
            "vs20egypttrs" => "Egyptian Fortunes",
            "vs50safariking" => "Safari King",
            "vs50pixie" => "Pixie Wings",
            "vs20ekingrr" => "Emerald King Rainbow Road",
            "vswaysbankbonz" => "Cash Bonanza",
            "vs20honey" => "Honey Honey Honey",
            "vs117649starz" => "Starz Megaways",
            "vs20santa" => "Santa",
            "vs20wildpix" => "Wild Pixies",
            "vs18mashang" => "Treasure Horse",
            "vs9madmonkey" => "Monkey Madness",
            "vs40madwheel" => "The Wild Machine",
            "vs20leprexmas" => "Leprechaun Carol",
            "vs9hotroll" => "Hot Chilli",
            "vs20chicken" => "The Great Chicken Escape",
            "vs10starpirate" => "Star Pirates Code",
            "vs20eking" => "Emerald King",
            "vs15fairytale" => "Fairytale Fortune",
            "vs20godiva" => "Lady Godiva",
            "vs40frrainbow" => "Fruit Rainbow",
            "vs50chinesecharms" => "Lucky Dragons",
            "vs4096mystery" => "Mysterious",
            "vs25safari" => "Hot Safari",
            "vs7pigs" => "7 Piggies",
            "vs8magicjourn" => "Magic Journey",
            "vs25walker" => "Wild Walker",
            "vs50kingkong" => "Mighty Kong",
            "vs5trdragons" => "Triple Dragons",
            "bndt" => "Dragon Tiger",
            "vs20leprechaun" => "Leprechaun Song",
            "vs10egypt" => "Ancient Egypt",
            "vs25dwarves_new" => "Dwarven Gold Deluxe",
            "vs20terrorv" => "Cash Elevator",
            "vs20cashmachine" => "Cash Box",
            "vs20mysteryst" => "Country Farming",
            "vs40mstrwild" => "Happy Hooves",
            "vs20splmystery" => "Spellbinding Mystery",
            "vs75bronco" => "Bronco Spirit",
            "vs75empress" => "Golden Beauty",
            "vs3train" => "Gold Train",
            "vs25queenofgold" => "Queen of Gold",
            "vs20gorilla" => "Jungle Gorilla",
            "1301" => "Spaceman",
            "vpdr7" => "Greyhound Racing",
            "vppso4" => "Penalty Shootout",
            "vpsc10" => "Steeplechase",
        ];
    }
}
